<Project Sdk="Microsoft.NET.Sdk.Web">

	<PropertyGroup>
		<TargetFramework>net10.0</TargetFramework>
		<Nullable>enable</Nullable>
		<ImplicitUsings>enable</ImplicitUsings>
		<UserSecretsId>cf9ceb15-af60-41d2-b37a-4885fae89b71</UserSecretsId>
	</PropertyGroup>

	<ItemGroup>
		<Compile Remove="Views\Admin\NewFolder\**" />
		<Content Remove="Views\Admin\NewFolder\**" />
		<EmbeddedResource Remove="Views\Admin\NewFolder\**" />
		<None Remove="Views\Admin\NewFolder\**" />
		<Compile Remove="TrendyKart.Tests\**" />
		<Content Remove="TrendyKart.Tests\**" />
		<EmbeddedResource Remove="TrendyKart.Tests\**" />
		<None Remove="TrendyKart.Tests\**" />
	</ItemGroup>

	<ItemGroup>
		<PackageReference Include="BCrypt.Net-Next" Version="4.1.0" />
		<PackageReference Include="Microsoft.AspNetCore.Authentication.Google" Version="10.0.0" />
		<PackageReference Include="Microsoft.Data.SqlClient" Version="6.1.4" />

		<!-- ✅ ALL EF PACKAGES SAME VERSION -->
		<PackageReference Include="Microsoft.EntityFrameworkCore" Version="10.0.3" />
		<PackageReference Include="Microsoft.EntityFrameworkCore.SqlServer" Version="10.0.3" />
		<PackageReference Include="Microsoft.EntityFrameworkCore.Design" Version="10.0.3">
			<PrivateAssets>all</PrivateAssets>
			<IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
		</PackageReference>
		<PackageReference Include="Microsoft.EntityFrameworkCore.Tools" Version="10.0.3">
			<PrivateAssets>all</PrivateAssets>
			<IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
		</PackageReference>

	</ItemGroup>

	<ItemGroup>
		<Folder Include="wwwroot\images\" />
	</ItemGroup>

</Project>